server:
  port: 8080
cloud:
  alibaba:
    pay:
      URL: https://openapi.alipay.com/gateway.do
      SIGN_TYPE: RSA2
      FORMAT: json
      CHARSET: utf-8
      APPID:
      PRIVATE_KEY:
      ALIPAY_PUBLIC_KEY:
      NOTIFY_URL: your_domain/alipay/callback/return
      RETURN_URL: your_domain/alipay/callback/notify
  tencent:
    wechat:
      pay:
        API_V3_KEY:
        MCH_ID:
        APP_ID:
        MCH_SERIAL_NO:
        MCH_PRIVATE_KEY_PATH:
        NOTIFY_URL:
spring:
  profiles:
    active: sandbox
    logging:
      level:
        root: info